name: Deploy to Heroku

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment:
            name: Heroku # naam van mijn environment op GitHub
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: chevy-shareameal-prog4
                  heroku_email: c.rietveld2@student.avans.nl
